apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ebodye1az-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ebodye1az-dotnet-basic-gitops